sudo: required
services:
  - docker

before_install: true
  
script: true

after_success:
  - docker build -t trishulb/nclient ./client
  - docker build -t trishulb/nserver ./server

# Log in into docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  
# take those imagases and push them to docker hub
  - docker push trishulb/nclient
  - docker push trishulb/nserver  
