sudo: required
services:
  - docker
  - node

before_install:
  - cd ./client
  - npm install
  - npm run build
  - docker build -t trishulb/nClient ./client

script:
  - docker run trishulb/nClient npm test -- --coverage

after-build:
  - docker build -t trishulb/nClient ./client
  - docker build -t trishulb/nServer ./server

# Log in into docker CLI
  - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
  
# take those imagases and push them to docker hub
  - docker push trishulb/nClient
  - docker push trishulb/nServer  
